apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvitae.fullname" . }}
  labels:
    {{- include "openvitae.labels" . | nindent 4 }}
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.auth.accessTokenExpireMinutes | quote }}
  ADMIN_EMAIL: {{ .Values.auth.admin.email | quote }}
  S3_ENDPOINT_URL: {{ include "openvitae.s3Endpoint" . | quote }}
  S3_PUBLIC_ENDPOINT_URL: {{ include "openvitae.s3PublicUrl" . | quote }}
  S3_BUCKET: {{ include "openvitae.s3Bucket" . | quote }}
  S3_REGION: {{ include "openvitae.s3Region" . | quote }}
  CORS_ORIGINS: {{ include "openvitae.corsOrigins" . | quote }}
