"""projects slug/content/screenshots, colored tags, skills

Revision ID: 11a2db3efb9b
Revises: ac4556687fcc
Create Date: 2026-06-23 07:13:03.006799

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "11a2db3efb9b"
down_revision: str | None = "ac4556687fcc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_skills_slug"), "skills", ["slug"], unique=True)
    op.create_table(
        "project_skills",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "skill_id"),
    )
    op.create_table(
        "project_tags",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "tag_id"),
    )
    op.add_column("projects", sa.Column("slug", sa.String(length=512), nullable=True))
    op.add_column("projects", sa.Column("content", sa.Text(), nullable=True))
    op.add_column(
        "projects",
        sa.Column(
            "screenshot_keys",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # Backfill a unique slug for any pre-existing rows before enforcing NOT NULL/unique.
    op.execute("UPDATE projects SET slug = 'project-' || id WHERE slug IS NULL")
    op.alter_column("projects", "slug", nullable=False)
    op.create_index(op.f("ix_projects_slug"), "projects", ["slug"], unique=True)
    op.add_column("tags", sa.Column("color", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "color")
    op.drop_index(op.f("ix_projects_slug"), table_name="projects")
    op.drop_column("projects", "screenshot_keys")
    op.drop_column("projects", "content")
    op.drop_column("projects", "slug")
    op.drop_table("project_tags")
    op.drop_table("project_skills")
    op.drop_index(op.f("ix_skills_slug"), table_name="skills")
    op.drop_table("skills")
    # ### end Alembic commands ###
