"""skill color

Revision ID: 6c64c3860cad
Revises: 11a2db3efb9b
Create Date: 2026-06-23 07:40:14.355801

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6c64c3860cad"
down_revision: str | None = "11a2db3efb9b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skills", sa.Column("color", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "color")
    # ### end Alembic commands ###
