"""talk file

Revision ID: 8438d861a915
Revises: 6c64c3860cad
Create Date: 2026-06-23 07:52:33.470743

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8438d861a915'
down_revision: str | None = '6c64c3860cad'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talks', sa.Column('file_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('talks', 'file_key')
    # ### end Alembic commands ###
