"""site pages

Revision ID: dda470566770
Revises: 8438d861a915
Create Date: 2026-10-09 09:30:48.237188

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dda470566770'
down_revision: str | None = '8438d861a915'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_config', sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_config', 'pages')
    # ### end Alembic commands ###
